import {Toaster} from "@/components/ui/sonner";
import {TRPCProvider} from "@/trpc/client";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
									   children,
								   }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<TRPCProvider>
			<body
				className={` ${inter.className} antialiased`}
			>
			<Toaster/>
			{children}
			</body>
		</TRPCProvider>
		</html>
	);
}
